#!/bin/bash

# Find connected displays
CONNECTED=($(xrandr | grep " connected" | awk '{print $1}'))

# Detect internal display (eDP or LVDS)
INTERNAL=$(printf "%s\n" "${CONNECTED[@]}" | grep -E "^eDP|^LVDS" | head -n 1)

# If no internal detected, use the display marked primary
if [[ -z "$INTERNAL" ]]; then
    INTERNAL=$(xrandr | grep " primary" | awk '{print $1}')
fi

# Get external displays
EXTERNALS=($(printf "%s\n" "${CONNECTED[@]}" | grep -v "$INTERNAL"))

echo "Internal display: $INTERNAL"
echo "External displays: ${EXTERNALS[*]}"

CONFIG_FILE="${HOME}/.config/i3/workspace-outputs.conf"

write_dual_output_config() {
    local LEFT="$1"
    local RIGHT="$2"
    {
        echo "# Autogenerated"
        echo "workspace 1 output $LEFT"
        echo "workspace 2 output $RIGHT"
        echo "workspace 3 output $LEFT"
        echo "workspace 4 output $RIGHT"
        echo "workspace 5 output $LEFT"
        echo "workspace 6 output $RIGHT"
        echo "workspace 7 output $LEFT"
        echo "workspace 8 output $RIGHT"
    } > "$CONFIG_FILE"
}

clear_output_config() {
    : > "$CONFIG_FILE"
}

reload_i3() {
    i3-msg reload >/dev/null 2>&1 || true
}

# If no external monitors → laptop only
if [[ ${#EXTERNALS[@]} -eq 0 ]]; then
    echo "No externals → Using internal screen only."
    xrandr --output "$INTERNAL" --auto --primary
    clear_output_config
    reload_i3
    exit 0
fi

echo "External monitors detected → disabling internal."
xrandr --output "$INTERNAL" --off

# Randomize order (creates random left↔right placement)
shuf_externals=($(printf "%s\n" "${EXTERNALS[@]}" | shuf))

echo "Randomized external order: ${shuf_externals[*]}"

# Place the externals side by side
POS=0
PRIMARY_SET=0

for EXT in "${shuf_externals[@]}"; do
    echo " → Activating $EXT at ${POS}x0"
    xrandr --output "$EXT" --auto --pos ${POS}x0

    # Set first (randomly chosen) as primary
    if [[ $PRIMARY_SET -eq 0 ]]; then
        xrandr --output "$EXT" --primary
        PRIMARY_SET=1
    fi

    # Determine width of this display
    WIDTH=$(xrandr | awk -v e="$EXT" '
        $0 ~ ("^"e" ") {f=1}
        f && /\*/ {split($1,a,"x"); print a[1]; exit}
    ')

    POS=$(( POS + WIDTH ))
done

# Write i3 workspace rules only when exactly 2 external monitors are present
if [[ ${#shuf_externals[@]} -eq 2 ]]; then
    LEFT="${shuf_externals[0]}"
    RIGHT="${shuf_externals[1]}"
    echo "Writing odd/even workspace rules: odd -> $LEFT, even -> $RIGHT"
    write_dual_output_config "$LEFT" "$RIGHT"
else
    echo "Not exactly 2 externals → clearing i3 workspace rules"
    clear_output_config
fi

reload_i3
